### ISSUE TITLE
Changelog usando pipeline

### ISSUE THREAD

**Issue by bmsrox** [juniorjbn/php-test#1]
Ea João blz ? Cara tem algum material sobre esse assunto. Ou exemplos ? Ou tenho q fazer na mão? rs

**Comment by juniorjbn** [comment]
Falaí !
Cara, tenho um vídeo e um blog post sobre isso:
https://youtu.be/fYrLA8yqZnI
https://blog.getupcloud.com/work-smarter-not-harder-f68282cebf41

Qqer coisa, chama ai!
